CREATE TABLE IF NOT EXISTS t_agent_model_route (
    id BIGINT PRIMARY KEY,
    route_key VARCHAR(32) NOT NULL UNIQUE,
    model VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    rollout_percent INTEGER NOT NULL DEFAULT 100,
    updated_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
