ALTER TABLE t_knowledge_graph_node ADD COLUMN IF NOT EXISTS confidence NUMERIC(4,3) NOT NULL DEFAULT 0.700;
ALTER TABLE t_knowledge_graph_edge ADD COLUMN IF NOT EXISTS confidence NUMERIC(4,3) NOT NULL DEFAULT 0.700;
