<template>
  <main class="agent-admin page">
    <div class="container">
      <header><span>AGENT OPERATIONS</span><h1>Agent control room</h1><p>Index health, retries, role management, and governance controls are protected by server-side permissions.</p></header>
      <section v-if="error" class="card error">{{ error }}</section>
      <template v-else>
        <section class="card roles"><div class="section-head"><h2>Graph maintenance</h2><small>Re-extracts verified claims from durable chunks without crawling a book source.</small></div><form @submit.prevent="rebuildGraph"><input v-model.number="rebuildBookId" required min="1" type="number" placeholder="Canonical book ID" /><button :disabled="rebuilding">{{ rebuilding ? 'Rebuilding...' : 'Rebuild graph' }}</button></form><p v-if="rebuildError" class="error-text">{{ rebuildError }}</p><form @submit.prevent="loadGraphReviewClaims"><input v-model.number="reviewBookId" required min="1" type="number" placeholder="Work ID for claim review" /><button :disabled="loadingReview">{{ loadingReview ? 'Loading...' : 'Load pending claims' }}</button></form><p v-if="reviewError" class="error-text">{{ reviewError }}</p><div v-for="claim in reviewClaims" :key="`${claim.claimType}-${claim.id}`" class="job"><span><b>{{ claim.claimType }}</b> · {{ claim.label }} · Ch. {{ (claim.firstChapter || 0) + 1 }}<small>{{ claim.reviewStatus }} · {{ claim.confidence }} · {{ claim.sourceModelVersion }}</small><small>{{ claim.evidence }}</small></span><span><button @click="reviewClaim(claim, 'APPROVED')">Approve</button><button @click="reviewClaim(claim, 'REJECTED')">Reject</button></span></div></section>
        <section class="admin-grid"><article v-for="item in statCards" :key="item.label" class="card"><small>{{ item.label }}</small><strong>{{ item.value }}</strong></article></section><section class="card jobs"><h2>7-day model usage</h2><p>Requests {{ usage.requests || 0 }} · tokens {{ usage.estimatedTokens || 0 }} · provider reported {{ usage.providerReportedRequests || 0 }} · estimated {{ usage.estimatedUsageRequests || 0 }} · platform cost CNY {{ ((usage.platformCostMicros || 0) / 1000000).toFixed(4) }} · fallback {{ usage.degraded || 0 }} · platform {{ usage.platformRequests || 0 }} · BYOK {{ usage.byokRequests || 0 }}</p></section>
        <section class="card jobs"><div class="section-head"><h2>LightRAG prompt budget</h2><small>Privacy-safe section totals; prompt text, user IDs and request IDs are never returned.</small></div><p>Requests {{ usageBreakdown.requests || 0 }} · composition-covered {{ usageBreakdown.sectionCompositionRequests || 0 }}</p><div class="budget-grid"><span v-for="(value, key) in (usageBreakdown.sectionTokens || {})" :key="key"><b>{{ key }}</b><small>{{ value }} tokens</small></span></div><div v-for="row in (usageBreakdown.recent || []).slice(0, 8)" :key="`${row.createdAt}-${row.graphTokens}-${row.evidenceTokens}`" class="job"><span>{{ row.createdAt }} · {{ row.status }}</span><small>graph {{ row.graphTokens }} · community {{ row.communityTokens }} · evidence {{ row.evidenceTokens }} · {{ row.tokenUsageSource }}</small></div></section>
        <section class="card jobs"><h2>Recent index jobs</h2><p v-if="!jobs.length">No recent jobs.</p><div v-for="job in jobs" :key="job.id" class="job"><span><b>{{ job.status }}</b> · Work {{ job.canonicalBookId }} · {{ job.jobType }}</span><button v-if="job.status === 'FAILED'" :disabled="retrying === job.id" @click="retry(job.id)">{{ retrying === job.id ? 'Retrying...' : 'Retry' }}</button></div></section>
        <section class="card roles"><div class="section-head"><h2>Agent roles</h2><small>Only ADMIN may grant or revoke persistent roles.</small></div><form @submit.prevent="saveRole"><input v-model="roleForm.userId" type="number" min="1" required placeholder="User ID" /><select v-model="roleForm.roleCode"><option value="OPERATOR">OPERATOR</option><option value="ADMIN">ADMIN</option></select><button>Grant role</button></form><p v-if="roleError" class="error-text">{{ roleError }}</p><div v-for="role in roles" :key="role.userId" class="job"><span><b>{{ role.roleCode }}</b> · User {{ role.userId }}</span><button @click="removeRole(role.userId)">Revoke</button></div></section>
        <section class="card roles"><div class="section-head"><h2>Prompt versions</h2><small>Publishing creates and activates a version; a previous version can be restored.</small></div><form class="prompt-form" @submit.prevent="savePrompt"><textarea v-model="promptContent" required maxlength="4000" placeholder="Additional administrator policy" /><button>Publish prompt</button></form><p v-if="promptError" class="error-text">{{ promptError }}</p><div v-for="prompt in promptVersions" :key="prompt.id" class="job"><span><b>v{{ prompt.versionNo }}</b> · {{ prompt.active ? 'ACTIVE' : 'archived' }}</span><span><small>{{ prompt.createdAt }}</small><button v-if="!prompt.active" @click="activatePrompt(prompt.id)">Restore</button></span></div></section>
        <section class="card roles"><div class="section-head"><h2>Model routes</h2><small>FAST、STRONG 和 RERANKER 均支持稳定的百分比分桶灰度。</small></div><form @submit.prevent="saveRoute"><select v-model="routeForm.routeKey"><option value="FAST">FAST</option><option value="STRONG">STRONG</option><option value="RERANKER">RERANKER</option></select><input v-model="routeForm.model" required placeholder="Model name" /><input v-model.number="routeForm.rolloutPercent" required type="number" min="0" max="100" /><button>Save route</button></form><p v-if="routeError" class="error-text">{{ routeError }}</p><div v-for="route in modelRoutes" :key="route.id" class="job"><span><b>{{ route.routeKey }}</b> · {{ route.model }}</span><small>{{ route.enabled ? `${route.rolloutPercent}% rollout` : 'disabled' }}</small></div></section>
        <section class="card roles"><div class="section-head"><h2>Platform model pricing</h2><small>Versioned micro-CNY prices per thousand tokens. BYOK is excluded.</small></div><form @submit.prevent="savePricing"><input v-model="pricingForm.provider" required placeholder="Provider" /><input v-model="pricingForm.model" required placeholder="Model" /><input v-model.number="pricingForm.inputCostMicrosPerThousand" required type="number" min="0" placeholder="Input micro-CNY" /><input v-model.number="pricingForm.outputCostMicrosPerThousand" required type="number" min="0" placeholder="Output micro-CNY" /><input v-model="pricingForm.pricingVersion" required placeholder="Price version" /><button>Save price</button></form><p v-if="pricingError" class="error-text">{{ pricingError }}</p><div v-for="price in modelPricing" :key="price.id" class="job"><span><b>{{ price.provider }}/{{ price.model }}</b> · v{{ price.pricingVersion }}</span><small>{{ price.enabled ? `${price.inputCostMicrosPerThousand}/${price.outputCostMicrosPerThousand} micro-CNY` : 'disabled' }}</small></div></section>
        <section class="card roles"><div class="section-head"><h2>Recommendation experiment</h2><small>Stable user buckets compare semantic-first and continuation-first ranking.</small></div><form @submit.prevent="saveExperiment"><label class="switch-line"><input v-model="experimentForm.enabled" type="checkbox" /> Enable experiment</label><input v-model.number="experimentForm.treatmentPercent" required type="number" min="0" max="100" /><button>Save experiment</button></form><p v-if="experimentError" class="error-text">{{ experimentError }}</p><p class="experiment-metrics"><b>Control</b> {{ experimentMetrics.control?.exposures || 0 }} exposures / {{ experimentMetrics.control?.positiveFeedback || 0 }} positive / {{ experimentMetrics.control?.addsToShelf || 0 }} adds<br /><b>Treatment</b> {{ experimentMetrics.treatment?.exposures || 0 }} exposures / {{ experimentMetrics.treatment?.positiveFeedback || 0 }} positive / {{ experimentMetrics.treatment?.addsToShelf || 0 }} adds</p></section>
        <section class="card roles"><div class="section-head"><h2>Evaluation release gates</h2><small>Persisted deterministic safety checks; run before changing prompts or model routes.</small></div><button @click="runEvaluation">Run policy suite</button><p v-if="evaluationError" class="error-text">{{ evaluationError }}</p><div v-for="run in evaluations" :key="run.id" class="job"><span><b>{{ run.status }}</b> 路 {{ run.suiteName }} 路 {{ run.passedCases }}/{{ run.totalCases }} passed</span><small>{{ run.createdAt }}</small></div></section>
        <section class="card roles"><div class="section-head"><h2>Model answer evidence</h2><small>Submit copyright-cleared model outputs. The server checks work IDs, citation chapter bounds, recommendation provenance, and write/tool safety before recording a release gate.</small></div><form class="prompt-form" @submit.prevent="recordAnswerEvaluation"><textarea v-model="answerEvaluationJson" required maxlength="60000" spellcheck="false" placeholder='{"suiteName":"model-answer-quality","model":"provider/model","promptVersion":"v1","cases":[{"caseId":"case-1","category":"QA","prompt":"...","answer":"...","readingBoundaryChapter":0,"canonicalBookId":1,"citationChapters":[0],"recommendationBookIds":[],"toolWritePerformed":false,"scopedToRequestingUser":true}]}' /><button :disabled="recordingAnswers">{{ recordingAnswers ? 'Checking evidence…' : 'Record answer suite' }}</button></form><p v-if="answerEvaluationError" class="error-text">{{ answerEvaluationError }}</p></section>
        <section class="card roles" v-if="evaluations.length"><div class="section-head"><h2>Evaluation case evidence</h2><small>Open a run to inspect persisted per-case scoring.</small></div><div v-for="run in evaluations" :key="`cases-${run.id}`" class="job"><span><b>{{ run.status }}</b> · {{ run.suiteName }}</span><button @click="toggleEvaluationCases(run.id)">{{ selectedEvaluationId === run.id ? 'Hide cases' : 'View cases' }}</button></div><div v-if="selectedEvaluationId" class="case-list"><p v-if="!evaluationCases.length">No per-case evidence was recorded for this run.</p><div v-for="item in evaluationCases" :key="item.id" class="job"><span><b>{{ item.status }}</b> · {{ item.category }} · {{ item.caseId }}</span><small>{{ item.score }}/100</small></div></div></section>
      </template>
    </div>
  </main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { apiActivateAgentPromptVersion, apiCreateAgentPromptVersion, apiDeleteAgentAdminRole, apiGetAgentAdminJobs, apiGetAgentAdminOverview, apiGetAgentUsageSummary, apiGetAgentUsageBreakdown, apiGetRecommendationExperiment, apiGetRecommendationExperimentMetrics, apiGetAgentEvaluations, apiGetAgentEvaluationCases, apiRecordAgentAnswerEvaluation, apiRunAgentPolicyEvaluation, apiListAgentAdminRoles, apiListAgentModelRoutes, apiListAgentModelPricing, apiListAgentPromptVersions, apiRebuildAgentGraph, apiGetAgentGraphReviewClaims, apiReviewAgentGraphClaim, apiRetryAgentAdminJob, apiSaveAgentAdminRole, apiSaveAgentModelRoute, apiSaveAgentModelPricing, apiSaveRecommendationExperiment } from '@/api/agent'

const overview = ref({}); const usage = ref({}); const usageBreakdown = ref({}); const jobs = ref([]); const roles = ref([]); const promptVersions = ref([]); const modelRoutes = ref([]); const modelPricing = ref([]); const evaluations = ref([]); const evaluationCases = ref([]); const reviewClaims = ref([]); const selectedEvaluationId = ref(null); const error = ref(''); const roleError = ref(''); const promptError = ref(''); const routeError = ref(''); const pricingError = ref(''); const experimentError = ref(''); const evaluationError = ref(''); const answerEvaluationError = ref(''); const rebuildError = ref(''); const reviewError = ref(''); const promptContent = ref(''); const answerEvaluationJson = ref(''); const retrying = ref(null); const rebuildBookId = ref(''); const reviewBookId = ref(''); const rebuilding = ref(false); const loadingReview = ref(false); const recordingAnswers = ref(false)
const roleForm = ref({ userId: '', roleCode: 'OPERATOR' })
const routeForm = ref({ routeKey: 'FAST', model: '', rolloutPercent: 100, enabled: true })
const pricingForm = ref({ provider: '', model: '', inputCostMicrosPerThousand: 0, outputCostMicrosPerThousand: 0, pricingVersion: 'v1', enabled: true })
const experimentForm = ref({ enabled: false, treatmentPercent: 0 })
const experimentMetrics = ref({ control: {}, treatment: {} })
const statCards = computed(() => [{ label: 'Index jobs', value: overview.value.total ?? 0 }, { label: 'Completed', value: overview.value.completed ?? 0 }, { label: 'Failed', value: overview.value.failed ?? 0 }, { label: 'Pending', value: overview.value.pending ?? 0 }])
async function load () { overview.value = await apiGetAgentAdminOverview(); usage.value = await apiGetAgentUsageSummary(); usageBreakdown.value = await apiGetAgentUsageBreakdown(); jobs.value = await apiGetAgentAdminJobs(); roles.value = await apiListAgentAdminRoles(); promptVersions.value = await apiListAgentPromptVersions(); modelRoutes.value = await apiListAgentModelRoutes(); modelPricing.value = await apiListAgentModelPricing(); evaluations.value = await apiGetAgentEvaluations(); const experiment = await apiGetRecommendationExperiment(); experimentMetrics.value = await apiGetRecommendationExperimentMetrics(); if (experiment) experimentForm.value = { enabled: experiment.enabled, treatmentPercent: experiment.treatmentPercent } }
async function retry (id) { retrying.value = id; try { await apiRetryAgentAdminJob(id); await load() } finally { retrying.value = null } }
async function rebuildGraph () { if (!window.confirm(`Rebuild graph claims for work ${rebuildBookId.value}?`)) return; rebuilding.value = true; rebuildError.value = ''; try { await apiRebuildAgentGraph(rebuildBookId.value); rebuildBookId.value = ''; await load() } catch (e) { rebuildError.value = e.message || 'Graph rebuild failed.' } finally { rebuilding.value = false } }
async function loadGraphReviewClaims () { reviewError.value = ''; loadingReview.value = true; try { reviewClaims.value = await apiGetAgentGraphReviewClaims(reviewBookId.value) } catch (e) { reviewError.value = e.message || 'Could not load graph review claims.' } finally { loadingReview.value = false } }
async function reviewClaim (claim, reviewStatus) { reviewError.value = ''; try { await apiReviewAgentGraphClaim(reviewBookId.value, { claimType: claim.claimType, claimId: claim.id, reviewStatus }); await loadGraphReviewClaims() } catch (e) { reviewError.value = e.message || 'Could not update graph claim.' } }
async function saveRole () { roleError.value = ''; try { await apiSaveAgentAdminRole({ userId: Number(roleForm.value.userId), roleCode: roleForm.value.roleCode }); roleForm.value.userId = ''; await load() } catch (e) { roleError.value = e.message || 'Role update failed.' } }
async function removeRole (userId) { roleError.value = ''; try { await apiDeleteAgentAdminRole(userId); await load() } catch (e) { roleError.value = e.message || 'Role removal failed.' } }
async function savePrompt () { promptError.value = ''; try { await apiCreateAgentPromptVersion({ content: promptContent.value }); promptContent.value = ''; await load() } catch (e) { promptError.value = e.message || 'Prompt publication failed.' } }
async function activatePrompt (id) { promptError.value = ''; try { await apiActivateAgentPromptVersion(id); await load() } catch (e) { promptError.value = e.message || 'Prompt restore failed.' } }
async function saveRoute () { routeError.value = ''; try { await apiSaveAgentModelRoute(routeForm.value); routeForm.value.model = ''; await load() } catch (e) { routeError.value = e.message || 'Model route update failed.' } }
async function savePricing () { pricingError.value = ''; try { await apiSaveAgentModelPricing(pricingForm.value); pricingForm.value.model = ''; await load() } catch (e) { pricingError.value = e.message || 'Model price update failed.' } }
async function saveExperiment () { experimentError.value = ''; try { await apiSaveRecommendationExperiment(experimentForm.value); await load() } catch (e) { experimentError.value = e.message || 'Experiment update failed.' } }
async function runEvaluation () { evaluationError.value = ''; try { await apiRunAgentPolicyEvaluation(); await load() } catch (e) { evaluationError.value = e.message || 'Evaluation failed.' } }
async function recordAnswerEvaluation () { answerEvaluationError.value = ''; let payload; try { payload = JSON.parse(answerEvaluationJson.value) } catch (_) { answerEvaluationError.value = 'Enter valid JSON for the answer-evaluation suite.'; return } recordingAnswers.value = true; try { await apiRecordAgentAnswerEvaluation(payload); answerEvaluationJson.value = ''; await load() } catch (e) { answerEvaluationError.value = e.message || 'Answer evidence was rejected.' } finally { recordingAnswers.value = false } }
async function toggleEvaluationCases (runId) { if (selectedEvaluationId.value === runId) { selectedEvaluationId.value = null; evaluationCases.value = []; return } evaluationError.value = ''; try { evaluationCases.value = await apiGetAgentEvaluationCases(runId); selectedEvaluationId.value = runId } catch (e) { evaluationError.value = e.message || 'Could not load evaluation evidence.' } }
onMounted(async () => { try { await load() } catch (e) { error.value = e.message || 'Administrator access is required.' } })
</script>

<style scoped>
.agent-admin { min-height:70vh; padding:64px 0; background:linear-gradient(135deg,var(--paper-0),var(--gold-3)); }.agent-admin header span { color:var(--gold-0); letter-spacing:.16em; font-size:.75rem; }.agent-admin h1 { font-family:var(--font-serif); color:var(--ink-0); }.admin-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-top:28px; }.admin-grid article,.jobs,.roles { padding:22px; }.admin-grid article { display:grid; gap:8px; }.admin-grid strong { font-size:2rem; color:var(--gold-0); }.jobs,.roles { margin-top:18px; }.job { display:flex; justify-content:space-between; gap:12px; padding:12px 0; border-top:1px solid var(--paper-3); }.job button,.roles form button { border:1px solid var(--gold-1); border-radius:99px; background:transparent; color:var(--gold-0); padding:4px 11px; cursor:pointer; }.section-head { display:flex; justify-content:space-between; gap:12px; align-items:baseline; }.section-head small { color:var(--ink-4); }.budget-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin:16px 0; }.budget-grid span { display:grid; gap:4px; padding:10px; border:1px solid var(--paper-3); border-radius:var(--radius-sm); }.roles form { display:flex; gap:8px; margin:12px 0; }.roles input,.roles select { min-width:0; padding:8px; border:1px solid var(--paper-3); border-radius:var(--radius-sm); background:var(--paper-0); font:inherit; }.error,.error-text { color:#9d2f22; }.error { margin-top:24px; padding:20px; } @media(max-width:700px){.admin-grid{grid-template-columns:repeat(2,1fr)}.budget-grid{grid-template-columns:repeat(2,1fr)}.roles form,.section-head{flex-direction:column;align-items:stretch}}
</style>
