<template>
  <main class="agent-admin page">
    <div class="container">
      <header><span>智能体运营</span><h1>Agent 管理中心</h1><p>这里用于查看索引状态、处理失败任务、管理权限和调整安全策略；所有操作都受服务端权限保护。</p></header>
      <section v-if="error" class="card error">{{ error }}</section>
      <template v-else>
        <section class="card roles"><div class="section-head"><h2>图谱维护</h2><small>基于已持久化的章节块重新提取关系，不会重新爬取书源。</small></div><form @submit.prevent="rebuildGraph"><input v-model.number="rebuildBookId" required min="1" type="number" placeholder="作品主键" /><button :disabled="rebuilding">{{ rebuilding ? '重建中……' : '重建图谱' }}</button></form><p v-if="rebuildError" class="error-text">{{ rebuildError }}</p><form @submit.prevent="loadGraphReviewClaims"><input v-model.number="reviewBookId" required min="1" type="number" placeholder="待审核作品主键" /><button :disabled="loadingReview">{{ loadingReview ? '加载中……' : '查看待审核关系' }}</button></form><p v-if="reviewError" class="error-text">{{ reviewError }}</p><div v-for="claim in reviewClaims" :key="`${claim.claimType}-${claim.id}`" class="job"><span><b>{{ claim.claimType }}</b> · {{ claim.label }} · 第 {{ (claim.firstChapter || 0) + 1 }} 章<small>{{ claim.reviewStatus }} · 置信度 {{ claim.confidence }} · {{ claim.sourceModelVersion }}</small><small>{{ claim.evidence }}</small></span><span><button @click="reviewClaim(claim, 'APPROVED')">通过</button><button @click="reviewClaim(claim, 'REJECTED')">驳回</button></span></div></section>
        <section class="admin-grid"><article v-for="item in statCards" :key="item.label" class="card"><small>{{ item.label }}</small><strong>{{ item.value }}</strong></article></section><section class="card jobs"><h2>近 7 天模型用量</h2><p>请求 {{ usage.requests || 0 }} · Token {{ usage.estimatedTokens || 0 }} · 模型上报 {{ usage.providerReportedRequests || 0 }} · 估算 {{ usage.estimatedUsageRequests || 0 }} · 平台成本 ¥{{ ((usage.platformCostMicros || 0) / 1000000).toFixed(4) }} · 降级 {{ usage.degraded || 0 }} · 平台模型 {{ usage.platformRequests || 0 }} · 自带模型 {{ usage.byokRequests || 0 }}</p></section>
        <section class="card jobs"><div class="section-head"><h2>LightRAG 提示词预算</h2><small>仅返回隐私安全的分段统计，不返回提示词正文、用户标识或请求标识。</small></div><p>请求 {{ usageBreakdown.requests || 0 }} · 已记录分段构成 {{ usageBreakdown.sectionCompositionRequests || 0 }}</p><div class="budget-grid"><span v-for="(value, key) in (usageBreakdown.sectionTokens || {})" :key="key"><b>{{ key }}</b><small>{{ value }} Token</small></span></div><div v-for="row in (usageBreakdown.recent || []).slice(0, 8)" :key="`${row.createdAt}-${row.graphTokens}-${row.evidenceTokens}`" class="job"><span>{{ row.createdAt }} · {{ row.status }}</span><small>图谱 {{ row.graphTokens }} · 社区 {{ row.communityTokens }} · 证据 {{ row.evidenceTokens }} · {{ row.tokenUsageSource }}</small></div></section>
        <section class="card jobs"><h2>最近的索引任务</h2><p v-if="!jobs.length">暂无索引任务。</p><div v-for="job in jobs" :key="job.id" class="job"><span><b>{{ job.status }}</b> · 作品 {{ job.canonicalBookId }} · {{ job.jobType }}</span><button v-if="job.status === 'FAILED'" :disabled="retrying === job.id" @click="retry(job.id)">{{ retrying === job.id ? '重试中……' : '重试' }}</button></div></section>
        <section class="card roles"><div class="section-head"><h2>Agent 管理员</h2><small>只有 ADMIN 可以授予或撤销持久化角色。</small></div><form @submit.prevent="saveRole"><input v-model="roleForm.userId" type="number" min="1" required placeholder="用户 ID" /><select v-model="roleForm.roleCode"><option value="OPERATOR">运营</option><option value="ADMIN">管理员</option></select><button>授予角色</button></form><p v-if="roleError" class="error-text">{{ roleError }}</p><div v-for="role in roles" :key="role.userId" class="job"><span><b>{{ role.roleCode }}</b> · 用户 {{ role.userId }}</span><button @click="removeRole(role.userId)">撤销</button></div></section>
        <section class="card roles"><div class="section-head"><h2>提示词版本</h2><small>发布会创建并激活新版本，也可以恢复历史版本。</small></div><form class="prompt-form" @submit.prevent="savePrompt"><textarea v-model="promptContent" required maxlength="4000" placeholder="补充管理员策略" /><button>发布提示词</button></form><p v-if="promptError" class="error-text">{{ promptError }}</p><div v-for="prompt in promptVersions" :key="prompt.id" class="job"><span><b>v{{ prompt.versionNo }}</b> · {{ prompt.active ? '当前启用' : '已归档' }}</span><span><small>{{ prompt.createdAt }}</small><button v-if="!prompt.active" @click="activatePrompt(prompt.id)">恢复</button></span></div></section>
        <section class="card roles"><div class="section-head"><h2>模型路由</h2><small>FAST、STRONG 和 RERANKER 均支持稳定的百分比分桶灰度。</small></div><form @submit.prevent="saveRoute"><select v-model="routeForm.routeKey"><option value="FAST">FAST</option><option value="STRONG">STRONG</option><option value="RERANKER">RERANKER</option></select><input v-model="routeForm.model" required placeholder="模型名称" /><input v-model.number="routeForm.rolloutPercent" required type="number" min="0" max="100" /><button>保存路由</button></form><p v-if="routeError" class="error-text">{{ routeError }}</p><div v-for="route in modelRoutes" :key="route.id" class="job"><span><b>{{ route.routeKey }}</b> · {{ route.model }}</span><small>{{ route.enabled ? `${route.rolloutPercent}% 灰度` : '已停用' }}</small></div></section>
        <section class="card roles"><div class="section-head"><h2>平台模型计价</h2><small>按千 Token 保存版本化的微元价格，不计入用户自带模型。</small></div><form @submit.prevent="savePricing"><input v-model="pricingForm.provider" required placeholder="兼容标识" /><input v-model="pricingForm.model" required placeholder="模型名称" /><input v-model.number="pricingForm.inputCostMicrosPerThousand" required type="number" min="0" placeholder="输入 Token 微元" /><input v-model.number="pricingForm.outputCostMicrosPerThousand" required type="number" min="0" placeholder="输出 Token 微元" /><input v-model="pricingForm.pricingVersion" required placeholder="价格版本" /><button>保存价格</button></form><p v-if="pricingError" class="error-text">{{ pricingError }}</p><div v-for="price in modelPricing" :key="price.id" class="job"><span><b>{{ price.provider }}/{{ price.model }}</b> · v{{ price.pricingVersion }}</span><small>{{ price.enabled ? `${price.inputCostMicrosPerThousand}/${price.outputCostMicrosPerThousand} 微元` : '已停用' }}</small></div></section>
        <section class="card roles"><div class="section-head"><h2>推荐实验</h2><small>使用稳定用户分桶，对比语义优先与追更优先的排序策略。</small></div><form @submit.prevent="saveExperiment"><label class="switch-line"><input v-model="experimentForm.enabled" type="checkbox" /> 启用实验</label><input v-model.number="experimentForm.treatmentPercent" required type="number" min="0" max="100" /><button>保存实验</button></form><p v-if="experimentError" class="error-text">{{ experimentError }}</p><p class="experiment-metrics"><b>对照组</b> {{ experimentMetrics.control?.exposures || 0 }} 次曝光 / {{ experimentMetrics.control?.positiveFeedback || 0 }} 次正反馈 / {{ experimentMetrics.control?.addsToShelf || 0 }} 次加入书架<br /><b>实验组</b> {{ experimentMetrics.treatment?.exposures || 0 }} 次曝光 / {{ experimentMetrics.treatment?.positiveFeedback || 0 }} 次正反馈 / {{ experimentMetrics.treatment?.addsToShelf || 0 }} 次加入书架</p></section>
        <section class="card roles"><div class="section-head"><h2>评测发布门禁</h2><small>持久化的确定性安全检查，修改提示词或模型路由前应先运行。</small></div><button @click="runEvaluation">运行策略评测</button><p v-if="evaluationError" class="error-text">{{ evaluationError }}</p><div v-for="run in evaluations" :key="run.id" class="job"><span><b>{{ run.status }}</b> · {{ run.suiteName }} · 通过 {{ run.passedCases }}/{{ run.totalCases }}</span><small>{{ run.createdAt }}</small></div></section>
        <section class="card roles"><div class="section-head"><h2>模型回答证据</h2><small>提交已获得授权的模型输出，服务端会校验作品主键、引用章节边界、推荐来源和工具写入安全，再记录发布门禁。</small></div><form class="prompt-form" @submit.prevent="recordAnswerEvaluation"><textarea v-model="answerEvaluationJson" required maxlength="60000" spellcheck="false" placeholder="请粘贴评测 JSON" /><button :disabled="recordingAnswers">{{ recordingAnswers ? '校验中……' : '记录回答评测' }}</button></form><p v-if="answerEvaluationError" class="error-text">{{ answerEvaluationError }}</p></section>
        <section class="card roles" v-if="evaluations.length"><div class="section-head"><h2>评测用例证据</h2><small>打开某次运行，查看持久化的逐用例评分。</small></div><div v-for="run in evaluations" :key="`cases-${run.id}`" class="job"><span><b>{{ run.status }}</b> · {{ run.suiteName }}</span><button @click="toggleEvaluationCases(run.id)">{{ selectedEvaluationId === run.id ? '收起用例' : '查看用例' }}</button></div><div v-if="selectedEvaluationId" class="case-list"><p v-if="!evaluationCases.length">这次运行没有记录逐用例证据。</p><div v-for="item in evaluationCases" :key="item.id" class="job"><span><b>{{ item.status }}</b> · {{ item.category }} · {{ item.caseId }}</span><small>{{ item.score }}/100</small></div></div></section>
      </template>
    </div>
  </main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { apiActivateAgentPromptVersion, apiCreateAgentPromptVersion, apiDeleteAgentAdminRole, apiGetAgentAdminJobs, apiGetAgentAdminOverview, apiGetAgentUsageSummary, apiGetAgentUsageBreakdown, apiGetRecommendationExperiment, apiGetRecommendationExperimentMetrics, apiGetAgentEvaluations, apiGetAgentEvaluationCases, apiRecordAgentAnswerEvaluation, apiRunAgentPolicyEvaluation, apiListAgentAdminRoles, apiListAgentModelRoutes, apiListAgentModelPricing, apiListAgentPromptVersions, apiRebuildAgentGraph, apiGetAgentGraphReviewClaims, apiReviewAgentGraphClaim, apiRetryAgentAdminJob, apiSaveAgentAdminRole, apiSaveAgentModelRoute, apiSaveAgentModelPricing, apiSaveRecommendationExperiment } from '@/api/agent'
import { useConfirmDialog } from '@/composables/useConfirmDialog'

const { confirm } = useConfirmDialog()
const overview = ref({}); const usage = ref({}); const usageBreakdown = ref({}); const jobs = ref([]); const roles = ref([]); const promptVersions = ref([]); const modelRoutes = ref([]); const modelPricing = ref([]); const evaluations = ref([]); const evaluationCases = ref([]); const reviewClaims = ref([]); const selectedEvaluationId = ref(null); const error = ref(''); const roleError = ref(''); const promptError = ref(''); const routeError = ref(''); const pricingError = ref(''); const experimentError = ref(''); const evaluationError = ref(''); const answerEvaluationError = ref(''); const rebuildError = ref(''); const reviewError = ref(''); const promptContent = ref(''); const answerEvaluationJson = ref(''); const retrying = ref(null); const rebuildBookId = ref(''); const reviewBookId = ref(''); const rebuilding = ref(false); const loadingReview = ref(false); const recordingAnswers = ref(false)
const roleForm = ref({ userId: '', roleCode: 'OPERATOR' })
const routeForm = ref({ routeKey: 'FAST', model: '', rolloutPercent: 100, enabled: true })
const pricingForm = ref({ provider: '', model: '', inputCostMicrosPerThousand: 0, outputCostMicrosPerThousand: 0, pricingVersion: 'v1', enabled: true })
const experimentForm = ref({ enabled: false, treatmentPercent: 0 })
const experimentMetrics = ref({ control: {}, treatment: {} })
const statCards = computed(() => [{ label: 'Index jobs', value: overview.value.total ?? 0 }, { label: 'Completed', value: overview.value.completed ?? 0 }, { label: 'Failed', value: overview.value.failed ?? 0 }, { label: 'Pending', value: overview.value.pending ?? 0 }])
async function load () { overview.value = await apiGetAgentAdminOverview(); usage.value = await apiGetAgentUsageSummary(); usageBreakdown.value = await apiGetAgentUsageBreakdown(); jobs.value = await apiGetAgentAdminJobs(); roles.value = await apiListAgentAdminRoles(); promptVersions.value = await apiListAgentPromptVersions(); modelRoutes.value = await apiListAgentModelRoutes(); modelPricing.value = await apiListAgentModelPricing(); evaluations.value = await apiGetAgentEvaluations(); const experiment = await apiGetRecommendationExperiment(); experimentMetrics.value = await apiGetRecommendationExperimentMetrics(); if (experiment) experimentForm.value = { enabled: experiment.enabled, treatmentPercent: experiment.treatmentPercent } }
async function retry (id) { retrying.value = id; try { await apiRetryAgentAdminJob(id); await load() } finally { retrying.value = null } }
async function rebuildGraph () { if (!await confirm({ title: '重建知识图谱', message: `确定基于作品 ${rebuildBookId.value} 已保存的章节重新提取知识图谱吗？不会重新爬取书源。`, confirmText: '开始重建', tone: 'danger' })) return; rebuilding.value = true; rebuildError.value = ''; try { await apiRebuildAgentGraph(rebuildBookId.value); rebuildBookId.value = ''; await load() } catch (e) { rebuildError.value = e.message || '图谱重建失败。' } finally { rebuilding.value = false } }
async function loadGraphReviewClaims () { reviewError.value = ''; loadingReview.value = true; try { reviewClaims.value = await apiGetAgentGraphReviewClaims(reviewBookId.value) } catch (e) { reviewError.value = e.message || '无法加载待审核关系。' } finally { loadingReview.value = false } }
async function reviewClaim (claim, reviewStatus) { reviewError.value = ''; try { await apiReviewAgentGraphClaim(reviewBookId.value, { claimType: claim.claimType, claimId: claim.id, reviewStatus }); await loadGraphReviewClaims() } catch (e) { reviewError.value = e.message || '无法更新图谱关系。' } }
async function saveRole () { roleError.value = ''; try { await apiSaveAgentAdminRole({ userId: Number(roleForm.value.userId), roleCode: roleForm.value.roleCode }); roleForm.value.userId = ''; await load() } catch (e) { roleError.value = e.message || '角色更新失败。' } }
async function removeRole (userId) { roleError.value = ''; try { await apiDeleteAgentAdminRole(userId); await load() } catch (e) { roleError.value = e.message || '角色撤销失败。' } }
async function savePrompt () { promptError.value = ''; try { await apiCreateAgentPromptVersion({ content: promptContent.value }); promptContent.value = ''; await load() } catch (e) { promptError.value = e.message || '提示词发布失败。' } }
async function activatePrompt (id) { promptError.value = ''; try { await apiActivateAgentPromptVersion(id); await load() } catch (e) { promptError.value = e.message || '提示词恢复失败。' } }
async function saveRoute () { routeError.value = ''; try { await apiSaveAgentModelRoute(routeForm.value); routeForm.value.model = ''; await load() } catch (e) { routeError.value = e.message || '模型路由更新失败。' } }
async function savePricing () { pricingError.value = ''; try { await apiSaveAgentModelPricing(pricingForm.value); pricingForm.value.model = ''; await load() } catch (e) { pricingError.value = e.message || '模型价格更新失败。' } }
async function saveExperiment () { experimentError.value = ''; try { await apiSaveRecommendationExperiment(experimentForm.value); await load() } catch (e) { experimentError.value = e.message || '推荐实验更新失败。' } }
async function runEvaluation () { evaluationError.value = ''; try { await apiRunAgentPolicyEvaluation(); await load() } catch (e) { evaluationError.value = e.message || '评测运行失败。' } }
async function recordAnswerEvaluation () { answerEvaluationError.value = ''; let payload; try { payload = JSON.parse(answerEvaluationJson.value) } catch (_) { answerEvaluationError.value = '请输入格式正确的回答评测 JSON。'; return } recordingAnswers.value = true; try { await apiRecordAgentAnswerEvaluation(payload); answerEvaluationJson.value = ''; await load() } catch (e) { answerEvaluationError.value = e.message || '回答证据未通过校验。' } finally { recordingAnswers.value = false } }
async function toggleEvaluationCases (runId) { if (selectedEvaluationId.value === runId) { selectedEvaluationId.value = null; evaluationCases.value = []; return } evaluationError.value = ''; try { evaluationCases.value = await apiGetAgentEvaluationCases(runId); selectedEvaluationId.value = runId } catch (e) { evaluationError.value = e.message || '无法加载评测证据。' } }
onMounted(async () => { try { await load() } catch (e) { error.value = e.message || 'Administrator access is required.' } })
</script>

<style scoped>
.agent-admin { min-height:70vh; padding:64px 0; background:linear-gradient(135deg,var(--paper-0),var(--gold-3)); }.agent-admin header span { color:var(--gold-0); letter-spacing:.16em; font-size:.75rem; }.agent-admin h1 { font-family:var(--font-serif); color:var(--ink-0); }.admin-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-top:28px; }.admin-grid article,.jobs,.roles { padding:22px; }.admin-grid article { display:grid; gap:8px; }.admin-grid strong { font-size:2rem; color:var(--gold-0); }.jobs,.roles { margin-top:18px; }.job { display:flex; justify-content:space-between; gap:12px; padding:12px 0; border-top:1px solid var(--paper-3); }.job button,.roles form button { border:1px solid var(--gold-1); border-radius:99px; background:transparent; color:var(--gold-0); padding:4px 11px; cursor:pointer; }.section-head { display:flex; justify-content:space-between; gap:12px; align-items:baseline; }.section-head small { color:var(--ink-4); }.budget-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin:16px 0; }.budget-grid span { display:grid; gap:4px; padding:10px; border:1px solid var(--paper-3); border-radius:var(--radius-sm); }.roles form { display:flex; gap:8px; margin:12px 0; }.roles input,.roles select { min-width:0; padding:8px; border:1px solid var(--paper-3); border-radius:var(--radius-sm); background:var(--paper-0); font:inherit; }.error,.error-text { color:#9d2f22; }.error { margin-top:24px; padding:20px; } @media(max-width:700px){.admin-grid{grid-template-columns:repeat(2,1fr)}.budget-grid{grid-template-columns:repeat(2,1fr)}.roles form,.section-head{flex-direction:column;align-items:stretch}}
</style>
